USE [HloMoney]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER TABLE [Contest]
ADD [Winners] INT

ALTER TABLE [Contest]
ADD [StartTime] DATETIME

CREATE TABLE [ContestPart]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[Contest] INT NOT NULL,
	[UserId] NVARCHAR(128) NOT NULL,

	CONSTRAINT [PK_dbo.ContestPart] PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)ON [PRIMARY];

CREATE TABLE [ContestWinner]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[Part] INT NOT NULL,
	
	CONSTRAINT [PK_dbo.ContestWinner] PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)ON [PRIMARY];

ALTER TABLE [dbo].[ContestPart]  WITH CHECK ADD  CONSTRAINT [FK_dbo.ContestPart_dbo.Contest_Id] FOREIGN KEY([Contest])
REFERENCES [dbo].[Contest] ([Id])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[ContestWinner]  WITH CHECK ADD  CONSTRAINT [FK_dbo.ContestWinner_dbo.ContestPart_Id] FOREIGN KEY([Part])
REFERENCES [dbo].[ContestPart] ([Id])
ON DELETE CASCADE
GO