USE [HloMoney]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [ContestPartError]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[Contest] INT NOT NULL,
	[Error] NVARCHAR(128) NOT NULL,

	CONSTRAINT [PK_dbo.ContestPartError] PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)ON [PRIMARY];

ALTER TABLE [dbo].[ContestPartError]  WITH CHECK ADD  CONSTRAINT [FK_dbo.ContestPartError_dbo.Contest_Id] FOREIGN KEY([Contest])
REFERENCES [dbo].[Contest] ([Id])
ON DELETE CASCADE
GO